---

# restart haproxy service
- name: restart haproxy
  systemd:
    name: haproxy
    daemon_reload: yes
    state: restarted

# restart keepalived service
- name: restart keepalived
  systemd:
    name: keepalived
    daemon_reload: yes
    state: restarted
    
...
